# 기반 이미지로 nginx 공식 이미지를 사용
FROM nginx

# 로컬의 default.conf 파일을 nginx의 설정 디렉터리로 복사
COPY ./default.conf /etc/nginx/conf.d/default.conf

# 컨테이너가 시작될 때 nginx를 백그라운드에서 실행하지 않고, 포그라운드에서 실행하도록 설정
ENTRYPOINT ["nginx", "-g", "daemon off;"]